name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Auth
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: ls Command
        run: ls -l
      - name: Docker Build
        run: echo "Docker build CI"
  Tests:
    runs-on: ubuntu-latest
    needs: ["CI"]
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      #- name: Install dependencies
        #run: |
        #  install.packages(c("shinytest2"))
        #shell: Rscript {0}
      - name: wd
        run: |
          getwd()
        shell: Rscript {0}
      - name: list files
        run: |
          list.files()
        shell: Rscript {0}
  CD:
    runs-on: ubuntu-latest
    needs: ["CI", "Tests"]
    steps:
      - name: Deploy App
        run: echo "Deploy App"
